nginx:
  image: nginx:alpine
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - ./server.key:/etc/nginx/server.key:ro
    - ./server.crt:/etc/nginx/server.crt:ro
    - ./ca.crt:/etc/nginx/ca.crt:ro
    - ./index.html:/etc/nginx/html/index.html:ro
  ports:
    - "80:80"
    - "443:443"